### ISSUE TITLE
Beer Search

### ISSUE THREAD

**Issue by ThommiTom** [ThommiTom/HoldMyBeer#2]
## Description
This UI/View should enable the user to enter different data (e.g. abv, ibu, ebc, ...). The user input will then be used in a network call for an explicit beer search.

## ToDos
- [x] Build UI for user input
- [x] provide parameter explanation 
- [x] use user input in a network call to acquire data
